CREATE TABLE CHARA AS SELECT * FROM CSVREAD(chara.csv);
CREATE TABLE EQUIP AS SELECT * FROM CSVREAD(equip.csv);
CREATE TABLE EVENT AS SELECT * FROM CSVREAD(event.csv);
CREATE TABLE SUPPORT AS SELECT * FROM CSVREAD(support.csv);